<a href="https://colab.research.google.com/github/lupis30puc/bipm_text_analytics_exercises/blob/main/Exercise_3_Text_Representation_final_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import Binarizer
from gensim.corpora import Dictionary
from gensim.models import TfidfModel

### 2. Load stemmed dataset from exercise 2:

In [ ]:
stem_corpus = pickle.load(open('stem_corpus.pkl','rb'))

FileNotFoundError: ignored

In [ ]:
stem_corpus.head()

content  target  \
0  car wonder enlighten car saw dai door sport ca...       7   
1  clock poll final final clock report acceler cl...       4   
2  question folk mac plu final gave ghost weekend...       4   
3  weitek nntppostinghost amber ssd csd harri com...       1   
4  shuttl launch question articl cowcb world std ...      14   

            target_names  
0              rec.autos  
1  comp.sys.mac.hardware  
2  comp.sys.mac.hardware  
3          comp.graphics  
4              sci.space

In [ ]:
corpus = stem_corpus.content

In [ ]:
corpus[0]

'car wonder enlighten car saw dai door sport car look late earli call bricklin door small addit bumper separ rest bodi know tellm model engin spec year product car histori info funki look car email thank brought neighborhood lerxst'

In [ ]:
stem_corpus.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11314 entries, 0 to 11313
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   content       11314 non-null  object
 1   target        11314 non-null  int64 
 2   target_names  11314 non-null  object
dtypes: int64(1), object(2)
memory usage: 673.6+ KB


## 3. Bag-of-words (sklearn):
### a. Apply the following transformations to the stemmed data using the fit_transform() function. 
What is each of them doing? 
What are the pros and cons of each approach?

In [ ]:
approach_1 = CountVectorizer(max_df=0.95, min_df=0.05)

In [ ]:
#max_df= is to remove words that appear repetitive words
#min_df= is to remove words appearing very few times...

In [ ]:
transform_1 = approach_1.fit_transform(corpus)

In [ ]:
print(approach_1.get_feature_names()) #all stemmed words

['abl', 'accept', 'access', 'actual', 'address', 'advanc', 'ago', 'agre', 'allow', 'answer', 'anybodi', 'appreci', 'apr', 'area', 'articl', 'ask', 'assum', 'avail', 'awai', 'bad', 'base', 'believ', 'best', 'better', 'big', 'bit', 'book', 'bui', 'call', 'car', 'card', 'care', 'case', 'caus', 'chang', 'check', 'chip', 'christian', 'claim', 'close', 'com', 'come', 'complet', 'consid', 'control', 'correct', 'cost', 'cours', 'current', 'dai', 'data', 'david', 'deal', 'design', 'differ', 'discuss', 'drive', 'edu', 'effect', 'email', 'end', 'engin', 'exampl', 'exist', 'expect', 'experi', 'fact', 'far', 'fax', 'feel', 'file', 'final', 'follow', 'free', 'game', 'gener', 'get', 'given', 'go', 'god', 'good', 'got', 'govern', 'great', 'group', 'guess', 'gui', 'hand', 'happen', 'hard', 'have', 'heard', 'help', 'high', 'home', 'hope', 'human', 'idea', 'import', 'includ', 'info', 'inform', 'interest', 'internet', 'isn', 'issu', 'john', 'kei', 'kill', 'kind', 'know', 'larg', 'law', 'left', 'let', 'lif

In [ ]:
print(transform_1[0])

  (0, 29)	5
  (0, 225)	1
  (0, 49)	1
  (0, 123)	2
  (0, 28)	1
  (0, 186)	1
  (0, 110)	1
  (0, 61)	1
  (0, 234)	1
  (0, 100)	1
  (0, 59)	1
  (0, 203)	1


In [ ]:
print(transform_1.toarray())# the matrix: rows are count in each content[n], columns: words

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
approach_2 = TfidfVectorizer(max_df=0.95, min_df=0.05,use_idf=False, norm='l1')

You remove it to get relative frequencies, and change to norm : l1 (against norm l2, L squared, this is when you want to amplify things, )

it is tricky to modify the idf, it applies to the frequency...
The results are different



In [ ]:
transform_2 = approach_2.fit_transform(corpus)

In [ ]:
print(approach_2.get_feature_names())

['abl', 'accept', 'access', 'actual', 'address', 'advanc', 'ago', 'agre', 'allow', 'answer', 'anybodi', 'appreci', 'apr', 'area', 'articl', 'ask', 'assum', 'avail', 'awai', 'bad', 'base', 'believ', 'best', 'better', 'big', 'bit', 'book', 'bui', 'call', 'car', 'card', 'care', 'case', 'caus', 'chang', 'check', 'chip', 'christian', 'claim', 'close', 'com', 'come', 'complet', 'consid', 'control', 'correct', 'cost', 'cours', 'current', 'dai', 'data', 'david', 'deal', 'design', 'differ', 'discuss', 'drive', 'edu', 'effect', 'email', 'end', 'engin', 'exampl', 'exist', 'expect', 'experi', 'fact', 'far', 'fax', 'feel', 'file', 'final', 'follow', 'free', 'game', 'gener', 'get', 'given', 'go', 'god', 'good', 'got', 'govern', 'great', 'group', 'guess', 'gui', 'hand', 'happen', 'hard', 'have', 'heard', 'help', 'high', 'home', 'hope', 'human', 'idea', 'import', 'includ', 'info', 'inform', 'interest', 'internet', 'isn', 'issu', 'john', 'kei', 'kill', 'kind', 'know', 'larg', 'law', 'left', 'let', 'lif

In [ ]:
print(transform_2[0])

  (0, 29)	0.29411764705882354
  (0, 225)	0.058823529411764705
  (0, 49)	0.058823529411764705
  (0, 123)	0.11764705882352941
  (0, 28)	0.058823529411764705
  (0, 186)	0.058823529411764705
  (0, 110)	0.058823529411764705
  (0, 61)	0.058823529411764705
  (0, 234)	0.058823529411764705
  (0, 100)	0.058823529411764705
  (0, 59)	0.058823529411764705
  (0, 203)	0.058823529411764705


In [ ]:
print(transform_2.toarray())

[[0.         0.         0.         ... 0.         0.         0.05882353]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.01724138 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.07142857 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
approach_3 = TfidfVectorizer(max_df=0.95, min_df=0.05, smooth_idf=False)

Many ways to change the frequencies and the smoothing techniques...

What smooth_idf=False does is:
 idf(t) = log [ n / df(t) ] + 1 
 This avoids the lose of data even if values appear in all documents. 

 Scikit learn has less options for modifying that gensim...

In [ ]:
transform_3 = approach_3.fit_transform(corpus)

In [ ]:
print(approach_3.get_feature_names()) #its the same features!!

['abl', 'accept', 'access', 'actual', 'address', 'advanc', 'ago', 'agre', 'allow', 'answer', 'anybodi', 'appreci', 'apr', 'area', 'articl', 'ask', 'assum', 'avail', 'awai', 'bad', 'base', 'believ', 'best', 'better', 'big', 'bit', 'book', 'bui', 'call', 'car', 'card', 'care', 'case', 'caus', 'chang', 'check', 'chip', 'christian', 'claim', 'close', 'com', 'come', 'complet', 'consid', 'control', 'correct', 'cost', 'cours', 'current', 'dai', 'data', 'david', 'deal', 'design', 'differ', 'discuss', 'drive', 'edu', 'effect', 'email', 'end', 'engin', 'exampl', 'exist', 'expect', 'experi', 'fact', 'far', 'fax', 'feel', 'file', 'final', 'follow', 'free', 'game', 'gener', 'get', 'given', 'go', 'god', 'good', 'got', 'govern', 'great', 'group', 'guess', 'gui', 'hand', 'happen', 'hard', 'have', 'heard', 'help', 'high', 'home', 'hope', 'human', 'idea', 'import', 'includ', 'info', 'inform', 'interest', 'internet', 'isn', 'issu', 'john', 'kei', 'kill', 'kind', 'know', 'larg', 'law', 'left', 'let', 'lif

In [ ]:
print(transform_3[0])

  (0, 203)	0.121682990038635
  (0, 59)	0.13619718354871735
  (0, 100)	0.17360510673829524
  (0, 234)	0.12205830867257342
  (0, 61)	0.17175464030050264
  (0, 110)	0.09716570435591144
  (0, 186)	0.1771717303583916
  (0, 28)	0.1510033429609071
  (0, 123)	0.23634859995373567
  (0, 49)	0.1407339623887973
  (0, 225)	0.16984862582327953
  (0, 29)	0.8508576182722584


In [ ]:
print(transform_3.toarray())

[[0.         0.         0.         ... 0.         0.         0.12205831]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.11702349 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.27801296 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


How many features are left in the dictionary in iii. and what are their names (Hint: Use get_feature_names())? 

Do the features make sense? Are they different to those in i. and ii.? 

What happens if you change max_df and min_df?

In [ ]:
len(approach_1.get_feature_names())

235

In [ ]:
#approach_1.get_feature_names()

In [ ]:
len(approach_2.get_feature_names())

235

In [ ]:
#approach_2.get_feature_names()

In [ ]:
len(approach_3.get_feature_names())

235

### b. Apply Binarizer() to the result from a. i. using again fit_transform(). 
What does the result stand for? What are its pros and cons?

In [ ]:
#turning floats in the matrix to 1 and 0
approach_4 = Binarizer()

In [ ]:
transform_4 = approach_4.fit_transform(transform_1)

In [ ]:
print

In [ ]:
print(transform_4.toarray())

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### c. Put the frequencies for the first document from a. and b. in a data frame with a column keys containing the feature names from a. and four additional columns with the corresponding frequencies from a. and b. (Hint: Convert the corpus to an array first.).  Keep only those rows of the data frame with keys representing words that exist in the first document.

In [ ]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#import pandas as pd

#vect = TfidfVectorizer()
#tfidf_matrix = vect.fit_transform(documents)
#df = pd.DataFrame(tfidf_matrix.toarray(), columns = vect.get_feature_names())
#print(df)

In [ ]:
keys = approach_1.get_feature_names()
keys = np.asarray(keys) #converting corpus to np.array
df_1 = pd.DataFrame(data=keys) #creating the data frame
df_1.rename(columns={0 :'Key'}, inplace=True)
df_1.set_index('Key', inplace=True) #setting index as key
#adding the rest of the data
df_1['A1'], df_1['A2'], df_1['A3'], df_1['B'] = [transform_1[0].toarray()[0], transform_2[0].toarray()[0], transform_3[0].toarray()[0], transform_4[0].toarray()[0]]
df_1

A1        A2        A3  B
Key                                 
abl         0  0.000000  0.000000  0
accept      0  0.000000  0.000000  0
access      0  0.000000  0.000000  0
actual      0  0.000000  0.000000  0
address     0  0.000000  0.000000  0
...        ..       ...       ... ..
wrong       0  0.000000  0.000000  0
wrote       0  0.000000  0.000000  0
xnewsread   0  0.000000  0.000000  0
ye          0  0.000000  0.000000  0
year        1  0.058824  0.122058  1

[235 rows x 4 columns]

In [ ]:
#removing rows with 0 occurance 
df_1 = df_1[(df_1.T != 0).any()]     
df_1

A1        A2        A3  B
Key                              
call     1  0.058824  0.151003  1
car      5  0.294118  0.850858  1
dai      1  0.058824  0.140734  1
email    1  0.058824  0.136197  1
engin    1  0.058824  0.171755  1
info     1  0.058824  0.173605  1
know     1  0.058824  0.097166  1
look     2  0.117647  0.236349  1
small    1  0.058824  0.177172  1
thank    1  0.058824  0.121683  1
wonder   1  0.058824  0.169849  1
year     1  0.058824  0.122058  1

### d. Sort the data frame (descending) on:
####         i. TF-IDF Frequencies
####         ii. Absolute Frequencies
Do you see differences? Why?

In [ ]:
#sorting 
print(df_1.sort_values(by=['A3'], ascending=False))
print(df_1.sort_values(by=['A1'], ascending=False))

        A1        A2        A3  B
Key                              
car      5  0.294118  0.850858  1
look     2  0.117647  0.236349  1
small    1  0.058824  0.177172  1
info     1  0.058824  0.173605  1
engin    1  0.058824  0.171755  1
wonder   1  0.058824  0.169849  1
call     1  0.058824  0.151003  1
dai      1  0.058824  0.140734  1
email    1  0.058824  0.136197  1
year     1  0.058824  0.122058  1
thank    1  0.058824  0.121683  1
know     1  0.058824  0.097166  1
        A1        A2        A3  B
Key                              
car      5  0.294118  0.850858  1
look     2  0.117647  0.236349  1
call     1  0.058824  0.151003  1
dai      1  0.058824  0.140734  1
email    1  0.058824  0.136197  1
engin    1  0.058824  0.171755  1
info     1  0.058824  0.173605  1
know     1  0.058824  0.097166  1
small    1  0.058824  0.177172  1
thank    1  0.058824  0.121683  1
wonder   1  0.058824  0.169849  1
year     1  0.058824  0.122058  1


## 4. Bag-of-words (gensim):

### a. Create a corpus as input for gensim with corpus_gen=[doc.split() for doc in data_stem]. What is this command exactly doing?

In [ ]:
corpus_gen=[doc.split() for doc in stem_corpus.content]

In [ ]:
corpus_gen[0]

['car',
 'wonder',
 'enlighten',
 'car',
 'saw',
 'dai',
 'door',
 'sport',
 'car',
 'look',
 'late',
 'earli',
 'call',
 'bricklin',
 'door',
 'small',
 'addit',
 'bumper',
 'separ',
 'rest',
 'bodi',
 'know',
 'tellm',
 'model',
 'engin',
 'spec',
 'year',
 'product',
 'car',
 'histori',
 'info',
 'funki',
 'look',
 'car',
 'email',
 'thank',
 'brought',
 'neighborhood',
 'lerxst']

### b. Create a gensim Dictionary() based on the corpus. Call it id2word. Apply to it id2word.filter_extremes(no_below=566, no_above=0.95). What is this method doing?

In [ ]:
id2word = Dictionary(corpus_gen)

In [ ]:
print(id2word)

Dictionary(80476 unique tokens: ['addit', 'bodi', 'bricklin', 'brought', 'bumper']...)


In [ ]:
id2word.filter_extremes(no_below=566, no_above=0.95)

In [ ]:
print(id2word)

Dictionary(235 unique tokens: ['call', 'car', 'dai', 'email', 'engin']...)


### c.Apply the following operations. What is each of them doing?

In [ ]:
#i.
print(id2word.token2id)
#token -> tokenId.

{'call': 0, 'car': 1, 'dai': 2, 'email': 3, 'engin': 4, 'info': 5, 'know': 6, 'look': 7, 'small': 8, 'thank': 9, 'wonder': 10, 'year': 11, 'answer': 12, 'base': 13, 'card': 14, 'edu': 15, 'experi': 16, 'final': 17, 'gui': 18, 'messag': 19, 'nntppostinghost': 20, 'number': 21, 'report': 22, 'send': 23, 'access': 24, 'actual': 25, 'advanc': 26, 'anybodi': 27, 'better': 28, 'bit': 29, 'expect': 30, 'feel': 31, 'good': 32, 'got': 33, 'great': 34, 'heard': 35, 'help': 36, 'life': 37, 'like': 38, 'line': 39, 'machin': 40, 'mayb': 41, 'new': 42, 'opinion': 43, 'peopl': 44, 'plai': 45, 'post': 46, 'price': 47, 'probabl': 48, 'question': 49, 'read': 50, 'real': 51, 'recent': 52, 'start': 53, 'take': 54, 'time': 55, 'us': 56, 'wai': 57, 'address': 58, 'articl': 59, 'chip': 60, 'com': 61, 'far': 62, 'inform': 63, 'person': 64, 'phone': 65, 'point': 66, 'pretti': 67, 'requir': 68, 'stuff': 69, 'system': 70, 'thing': 71, 'version': 72, 'write': 73, 'wrote': 74, 'xnewsread': 75, 'check': 76, 'mean':

In [ ]:
#ii. it only prints the keys
print(id2word.token2id.keys())

dict_keys(['call', 'car', 'dai', 'email', 'engin', 'info', 'know', 'look', 'small', 'thank', 'wonder', 'year', 'answer', 'base', 'card', 'edu', 'experi', 'final', 'gui', 'messag', 'nntppostinghost', 'number', 'report', 'send', 'access', 'actual', 'advanc', 'anybodi', 'better', 'bit', 'expect', 'feel', 'good', 'got', 'great', 'heard', 'help', 'life', 'like', 'line', 'machin', 'mayb', 'new', 'opinion', 'peopl', 'plai', 'post', 'price', 'probabl', 'question', 'read', 'real', 'recent', 'start', 'take', 'time', 'us', 'wai', 'address', 'articl', 'chip', 'com', 'far', 'inform', 'person', 'phone', 'point', 'pretti', 'requir', 'stuff', 'system', 'thing', 'version', 'write', 'wrote', 'xnewsread', 'check', 'mean', 'possibl', 'right', 'set', 'softwar', 'tell', 'understand', 'world', 'ye', 'agre', 'allow', 'apr', 'believ', 'come', 'consid', 'control', 'cost', 'cours', 'follow', 'given', 'govern', 'hand', 'hard', 'hope', 'idea', 'john', 'kill', 'make', 'need', 'power', 'reason', 'result', 'sai', 'se

In [ ]:
#iii.
print(id2word.dfs)

{1: 692, 10: 697, 2: 1334, 7: 2206, 0: 1061, 8: 592, 6: 3524, 4: 668, 11: 2023, 5: 641, 3: 1476, 9: 2040, 17: 575, 22: 603, 20: 2320, 15: 6239, 21: 1179, 16: 628, 23: 741, 19: 640, 14: 701, 13: 820, 12: 766, 18: 595, 49: 1774, 53: 1232, 37: 708, 57: 2197, 42: 2820, 40: 602, 29: 1000, 41: 807, 27: 568, 30: 582, 35: 728, 24: 638, 47: 614, 39: 929, 38: 3840, 52: 627, 48: 1118, 33: 1223, 31: 709, 28: 1218, 34: 964, 32: 2337, 43: 1073, 44: 2552, 56: 2519, 54: 632, 51: 906, 45: 763, 25: 1097, 36: 1627, 26: 652, 46: 1711, 50: 1489, 55: 2771, 61: 3897, 75: 625, 72: 961, 74: 808, 73: 6076, 59: 4995, 60: 580, 62: 953, 69: 571, 67: 652, 68: 734, 66: 1555, 58: 635, 65: 710, 63: 1110, 70: 607, 71: 2071, 64: 1246, 84: 1008, 85: 773, 77: 1484, 83: 732, 81: 667, 76: 636, 79: 1843, 80: 982, 78: 1205, 82: 1212, 110: 839, 101: 956, 88: 2729, 102: 765, 106: 941, 104: 1106, 93: 574, 105: 2183, 92: 912, 97: 838, 108: 686, 111: 1247, 90: 1673, 89: 1426, 99: 780, 112: 968, 86: 661, 98: 716, 100: 770, 94: 1026

In [ ]:
id2word.dfs?

In [ ]:
#Document frequencies: token_id -> how many documents contain this token.
#dict(**kwargs) -> new dictionary initialized with the name=value pairs
 #   in the keyword argument list.  For example:  dict(one=1, two=2)

In [ ]:
#iv. bag of words
corpus1=[id2word.doc2bow(doc) for doc in corpus_gen]

In [ ]:
print(corpus1[0])
print(type(corpus1))

[(0, 1), (1, 5), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2), (8, 1), (9, 1), (10, 1), (11, 1)]
<class 'list'>


In [ ]:
#v. 
corpus2=[[(token[0],(token[1]/sum(n for _, n in doc))) for token in doc]
for doc in corpus1]

In [ ]:
print(corpus2[0])

[(0, 0.058823529411764705), (1, 0.29411764705882354), (2, 0.058823529411764705), (3, 0.058823529411764705), (4, 0.058823529411764705), (5, 0.058823529411764705), (6, 0.058823529411764705), (7, 0.11764705882352941), (8, 0.058823529411764705), (9, 0.058823529411764705), (10, 0.058823529411764705), (11, 0.058823529411764705)]


In [ ]:
#vi. 
corpus3=[[(token[0],1) for token in doc] for doc in corpus1]

In [ ]:
print(corpus3[0])

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1)]


In [ ]:
#vii. 
tfidf=TfidfModel(dictionary=id2word, normalize=True)
corpus4=[tfidf[id2word.doc2bow(doc)] for doc in corpus_gen]

In [ ]:
print(corpus4[0])

[(0, 0.146733841685233), (1, 0.866148745091086), (2, 0.13253862095166563), (3, 0.12626749519075897), (4, 0.1754180689543496), (5, 0.17797594275794237), (6, 0.07231482893119194), (7, 0.20270943201189023), (8, 0.18290603656499477), (9, 0.10620472906785529), (10, 0.17278341187493057), (11, 0.10672352675158762)]


### d. Put all the frequencies from iv. to vii. in a data frame for the first document in the corpus. Add a column keys with the feature names. Compare the results with those from sklearn by merging the two data frames. Where do you think that the differences come from?

In [ ]:
keys = approach_1.get_feature_names()
keys = np.asarray(keys) #converting corpus to np.array
df_1 = pd.DataFrame(data=keys) #creating the data frame
df_1.rename(columns={0 :'Key'}, inplace=True)
df_1.set_index('Key', inplace=True) #setting index as key
#adding the rest of the data
df_1['A1'], df_1['A2'], df_1['A3'], df_1['B'] = [transform_1[0].toarray()[0], transform_2[0].toarray()[0], transform_3[0].toarray()[0], transform_4[0].toarray()[0]]
df_1

In [ ]:
df_2 = pd.DataFrame(data=(dict.fromkeys(corpus_gen[0])).keys()) #creating the data frame
df_2.rename(columns={0 :'Key'}, inplace=True)
df_2.set_index('Key', inplace=True) #setting index as key
#adding the rest of the data
df_2['corpus1'] = np.array(corpus1)
#df_2['corpus1'] = id2word.doc2bow(corpus_gen[0],allow_update=True)
df_2


ValueError: Length of values does not match length of index

In [ ]:
doc1_df2 = pd.DataFrame(data=(dict.fromkeys(corpus_gen[0])).keys()) 
doc1_df2.rename(columns={0 :'Key'}, inplace=True)
doc1_df2.set_index('Key', inplace=True) #setting index as key
#adding the rest of the data
doc1_df2['corpus1'] = id2word.doc2bow(corpus_gen[0],allow_update=True)
doc1_df['corpus2'] = [[(token[0],(token[1]/sum(n for _, n in doc))) for token in doc] for doc in corpus1] 
doc1_df2

## 5. Ngrams:

### a. Apply the following transformation to the stemmed data using fit_transform(): 
    CountVectorizer(ngram_range=(2, 2), max_df=0.95, min_df=0.05). 
### What is it doing? Print the corresponding features. What are the differences to the features in Question 3. and Question 4? What happens if you change the values of max_df and min_df?

In [ ]:
n_gram = CountVectorizer(ngram_range=(2, 2), max_df=0.95, min_df=0.05)

In [ ]:
transform_6 = n_gram.fit_transform(corpus)
feature_names = n_gram.get_feature_names()
print(feature_names)

['articl apr', 'edu write', 'write articl']


### b. Put the result in a data frame with columns=feature_names. Print the data frame head and the maximum values for each word. What do you notice?

In [ ]:
ngram_features = np.asarray(feature_names) #converting corpus to np.array
df_3 = pd.DataFrame(data=ngram_features) #creating the data frame
df_3.rename(columns={0: feature_names}, inplace=True)
df_3.set_index('feature_names', inplace=True) #setting index as key
df_3

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 1653, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


KeyError: "None of ['feature_names'] are in the columns"

In [ ]:
#REFERENCES
#https://www.machinelearningplus.com/nlp/gensim-tutorial/